// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmV-qi6BDhv8EtRixSbDMVIZqIAl8Ekw4',
    appId: '1:270806145578:web:ef8b0cb4c01f072342c153',
    messagingSenderId: '270806145578',
    projectId: 'ai-cattle-monitoring-system',
    authDomain: 'ai-cattle-monitoring-system.firebaseapp.com',
    storageBucket: 'ai-cattle-monitoring-system.firebasestorage.app',
    measurementId: 'G-HZRP5WG8PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvq_NTErapq8oUbL1TPo-0ffoyPkFmUdg',
    appId: '1:270806145578:android:ead2e1a440213bc942c153',
    messagingSenderId: '270806145578',
    projectId: 'ai-cattle-monitoring-system',
    storageBucket: 'ai-cattle-monitoring-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6eYdotuG_a2jVLdRb6oacBRVqr9r-kLU',
    appId: '1:270806145578:ios:5d5d5882463fd82142c153',
    messagingSenderId: '270806145578',
    projectId: 'ai-cattle-monitoring-system',
    storageBucket: 'ai-cattle-monitoring-system.firebasestorage.app',
    iosBundleId: 'com.example.cattleAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6eYdotuG_a2jVLdRb6oacBRVqr9r-kLU',
    appId: '1:270806145578:ios:5d5d5882463fd82142c153',
    messagingSenderId: '270806145578',
    projectId: 'ai-cattle-monitoring-system',
    storageBucket: 'ai-cattle-monitoring-system.firebasestorage.app',
    iosBundleId: 'com.example.cattleAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmV-qi6BDhv8EtRixSbDMVIZqIAl8Ekw4',
    appId: '1:270806145578:web:041e3e39def77b1d42c153',
    messagingSenderId: '270806145578',
    projectId: 'ai-cattle-monitoring-system',
    authDomain: 'ai-cattle-monitoring-system.firebaseapp.com',
    storageBucket: 'ai-cattle-monitoring-system.firebasestorage.app',
    measurementId: 'G-XR2DHWCF6E',
  );

}